import localFont from "next/font/local";
import "./globals.css";
import {Outfit} from "next/font/google"
import NextAuthProvider from "./_components/Nextauth";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] })
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <NextAuthProvider>

        {children}
        <ToastContainer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
